# -*- coding: utf-8 -*-
"""analise_visual.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTvpQvYz-OHk8agoz6U88QAMjdcjQHOC
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

def visualizar_dados():
    # 1. Carregar o arquivo CSV
    # Ajustamos o caminho para encontrar o arquivo na pasta 'data'
    caminho_arquivo = os.path.join('..', 'data', 'bitcoin_historico.csv')

    try:
        df = pd.read_csv(caminho_arquivo)

        # 2. Converter a coluna 'Data' para o formato datetime
        df['Data'] = pd.to_datetime(df['Data'])

        # Configurar a Data como índice (facilita o gráfico)
        df.set_index('Data', inplace=True)

        print("Primeiras 5 linhas dos dados:")
        print(df.head())

        # 3. Plotar o gráfico (Exigência do cronograma: plt.plot)
        plt.figure(figsize=(12, 6))
        plt.plot(df['Preco_Fechamento'], label='Preço Bitcoin (USD)', color='orange')

        plt.title('Histórico de Preço do Bitcoin')
        plt.xlabel('Ano')
        plt.ylabel('Preço (USD)')
        plt.legend()
        plt.grid(True)

        # Mostrar o gráfico
        plt.show()

    except FileNotFoundError:
        print("Erro: O arquivo 'bitcoin_historico.csv' não foi encontrado.")
        print("Por favor, execute o script de coleta primeiro.")

if __name__ == "__main__":
    visualizar_dados()