# -*- coding: utf-8 -*-
"""coleta_dados_v1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sl43N-VlSYBhnG7I8u-jXkut4LEKgo37
"""

import requests
import pandas as pd
import os
from datetime import datetime

# --- CONFIGURAÇÃO ---
# COLA AQUI A TUA CHAVE DA COINGECKO ENTRE AS ASPAS
MINHA_API_KEY = "CG-XXXXXXXXXXXXXXXXXXXXXXXX"
# --------------------

# URL da API Pública
url = "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart"

# Parâmetros da requisição (o que queremos)
parametros = {
    'vs_currency': 'usd',
    'days': 'max',
    'interval': 'daily'
}

# Cabeçalho de autenticação (Onde mostramos o "Bilhete de Identidade")
headers = {
    "accept": "application/json",
    "x-cg-demo-api-key": MINHA_API_KEY
}

def coletar_dados():
    print("A conectar à API do CoinGecko com autenticação...")

    # Adicionamos 'headers=headers' aqui para enviar a chave
    resposta = requests.get(url, params=parametros, headers=headers)

    if resposta.status_code == 200:
        dados = resposta.json()
        precos = dados['prices']
        volumes = dados['total_volumes']

        lista_final = []
        for i in range(len(precos)):
            timestamp = precos[i][0]
            preco = precos[i][1]
            # Proteção caso os tamanhos das listas sejam diferentes
            if i < len(volumes):
                volume = volumes[i][1]
            else:
                volume = 0

            data = datetime.fromtimestamp(timestamp / 1000).strftime('%Y-%m-%d')
            lista_final.append([data, preco, volume])

        df = pd.DataFrame(lista_final, columns=['Data', 'Preco_Fechamento', 'Volume'])

        # No Colab, salvamos na pasta local primeiro
        caminho_arquivo = 'bitcoin_historico.csv'
        df.to_csv(caminho_arquivo, index=False)

        print(f"Sucesso! Dados salvos em: {caminho_arquivo}")
        print(f"Total de dias coletados: {len(df)}")
        print("\n--- Amostra dos dados ---")
        print(df.head())

    else:
        print(f"Erro ao acessar a API: {resposta.status_code}")
        print("Mensagem:", resposta.text)

if __name__ == "__main__":
    coletar_dados()