# -*- coding: utf-8 -*-
"""coleta_qualitativa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5J6z0_M3-hG3URZN3qd3v-WrGqXhIpf
"""

# 1. Instalar biblioteca do Google News
!pip install gnews -q

from gnews import GNews
import pandas as pd
from datetime import datetime

def coletar_noticias():
    print("--- INICIANDO COLETA DE SENTIMENTO (GNEWS) ---")

    # Configurar o "Robô Jornalista"
    google_news = GNews(language='en', country='US', period='7d', max_results=20)

    # Termo de pesquisa
    termo = "Bitcoin crypto price"
    print(f"Pesquisando por: '{termo}'...")

    noticias = google_news.get_news(termo)

    lista_noticias = []

    for item in noticias:
        titulo = item['title']
        data_publicacao = item['published date']
        link = item['url']

        # Tentar limpar a data (O GNews retorna formato complexo)
        try:
            # Simplificação da data para salvar
            lista_noticias.append([data_publicacao, titulo, link])
        except:
            continue

    # Criar Tabela
    df_news = pd.DataFrame(lista_noticias, columns=['Data', 'Titulo', 'Link'])

    # Salvar
    df_news.to_csv('noticias_bitcoin.csv', index=False, sep=';')

    print(f"\nSucesso! {len(df_news)} notícias coletadas.")
    print("--- Exemplo das notícias ---")
    # Aumentar largura da coluna para ler o título
    pd.set_option('display.max_colwidth', 100)
    print(df_news[['Data', 'Titulo']].head())

if __name__ == "__main__":
    coletar_noticias()