# -*- coding: utf-8 -*-
"""engenharia_features.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gs2wIDvYzy3sFTh1O8jEXX4zUR_JZeIO
"""

# 1. Instalar biblioteca técnica (facilita os cálculos)
!pip install pandas_ta -q

import pandas as pd
import pandas_ta as ta # Biblioteca de Análise Técnica
import matplotlib.pyplot as plt

def criar_features():
    print("--- INICIANDO ENGENHARIA DE FEATURES ---")

    # Carregar o teu arquivo salvo anteriormente
    # Ajusta o nome se necessário (ex: bitcoin_historico (1).csv)
    caminho_arquivo = 'bitcoin_historico.csv'

    try:
        # Ler com as configurações brasileiras (ponto e vírgula)
        df = pd.read_csv(caminho_arquivo, sep=';', decimal=',')
        df['Data'] = pd.to_datetime(df['Data'])
        df.set_index('Data', inplace=True)

        # Ordenar por data (antigo -> novo) para os cálculos funcionarem
        df.sort_index(inplace=True)

        print(f"Dados carregados: {len(df)} linhas.")

        # --- CRIAÇÃO DOS INDICADORES (O 'Módulo de Features' do PDF) ---

        # 1. Média Móvel Simples (SMA) de 7 dias (Curto prazo)
        df['SMA_7'] = ta.sma(df['Preco_Fechamento'], length=7)

        # 2. Média Móvel Simples (SMA) de 21 dias (Médio prazo)
        df['SMA_21'] = ta.sma(df['Preco_Fechamento'], length=21)

        # 3. RSI (Relative Strength Index) - Padrão 14 dias
        df['RSI'] = ta.rsi(df['Preco_Fechamento'], length=14)

        # 4. Volatilidade (Desvio Padrão dos últimos 7 dias)
        df['Volatilidade'] = df['Preco_Fechamento'].rolling(7).std()

        # Remover dias que ficaram vazios (NaN) por causa dos cálculos iniciais
        df.dropna(inplace=True)

        print("Indicadores calculados com sucesso!")
        print(df[['Preco_Fechamento', 'SMA_7', 'RSI']].tail())

        # Salvar o novo arquivo "turbinado"
        df.to_csv('bitcoin_features_v2.csv', sep=';', decimal=',')
        print("\nArquivo salvo: 'bitcoin_features_v2.csv'")

        # --- VISUALIZAÇÃO ---
        plt.figure(figsize=(12, 8))

        # Gráfico 1: Preço e Médias
        plt.subplot(2, 1, 1)
        plt.plot(df.index, df['Preco_Fechamento'], label='Preço', color='black', alpha=0.5)
        plt.plot(df.index, df['SMA_7'], label='Média 7d', color='orange')
        plt.plot(df.index, df['SMA_21'], label='Média 21d', color='blue')
        plt.title('Preço vs Médias Móveis')
        plt.legend()
        plt.grid(True, alpha=0.3)

        # Gráfico 2: RSI
        plt.subplot(2, 1, 2)
        plt.plot(df.index, df['RSI'], label='RSI', color='purple')
        plt.axhline(70, color='red', linestyle='--', alpha=0.5) # Sobrecompra
        plt.axhline(30, color='green', linestyle='--', alpha=0.5) # Sobrevenda
        plt.title('RSI (Força do Movimento)')
        plt.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    except Exception as e:
        print(f"Erro: {e}")
        print("Verifique se o arquivo 'bitcoin_historico.csv' está na pasta.")

if __name__ == "__main__":
    criar_features()