# -*- coding: utf-8 -*-
"""prever_criptoIA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rd8IA2RG37pfrX8EQYkqDTtQ3EtXjje-
"""

# --- VERSÃO SEM PANDAS_TA (Native Pandas) ---
import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import load_model
from gnews import GNews
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import requests
import os

def calcular_rsi(series, period=14):
    """Calcula RSI manualmente usando Pandas puro"""
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).fillna(0)
    loss = (-delta.where(delta < 0, 0)).fillna(0)
    
    # Média Móvel Exponencial (Padrão do RSI)
    avg_gain = gain.ewm(com=period-1, min_periods=period).mean()
    avg_loss = loss.ewm(com=period-1, min_periods=period).mean()
    
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def pipeline_previsao_final():
    print("--- 🚀 INICIANDO SISTEMA (V4 - PANDAS NATIVO) ---")
    
    # 1. COLETA DE DADOS
    print("\n1. Baixando dados (CoinGecko)...")
    url = "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart"
    params = {'vs_currency': 'usd', 'days': '365', 'interval': 'daily'} 
    
    try:
        resp = requests.get(url, params=params)
        data = resp.json()
        prices = data['prices']
        volumes = data['total_volumes']
        
        lista = []
        for i in range(len(prices)):
            ts = prices[i][0]
            price = prices[i][1]
            vol = volumes[i][1] if i < len(volumes) else 0
            date = datetime.fromtimestamp(ts/1000).strftime('%Y-%m-%d')
            lista.append([date, price, vol])
            
        df = pd.DataFrame(lista, columns=['Data', 'Preco_Fechamento', 'Volume'])
        df['Data'] = pd.to_datetime(df['Data'])
        df.set_index('Data', inplace=True)
        
    except Exception as e:
        print(f"Erro CoinGecko: {e}")
        return

    # 2. SENTIMENTO
    print("2. Analisando Notícias...")
    try:
        google_news = GNews(language='en', country='US', period='2d', max_results=10) 
        news = google_news.get_news("Bitcoin crypto price")
        analyzer = SentimentIntensityAnalyzer()
        scores = [analyzer.polarity_scores(i['title'])['compound'] for i in news]
        sentimento_hoje = np.mean(scores) if scores else 0
    except:
        sentimento_hoje = 0
    
    print(f"   -> Sentimento Hoje: {sentimento_hoje:.4f}")
    
    # 3. FEATURES (SEM PANDAS_TA)
    print("3. Calculando Indicadores (Matemática Nativa)...")
    
    # Média Móvel Simples (SMA)
    df['SMA_7'] = df['Preco_Fechamento'].rolling(window=7).mean()
    df['SMA_21'] = df['Preco_Fechamento'].rolling(window=21).mean()
    
    # RSI (Função Manual)
    df['RSI'] = calcular_rsi(df['Preco_Fechamento'])
    
    # Sentimento
    df['Sentimento_Medio'] = 0 
    if not df.empty:
        df.iloc[-1, df.columns.get_loc('Sentimento_Medio')] = sentimento_hoje
    
    df.dropna(inplace=True)

    # 4. PREPARAÇÃO
    features = ['Preco_Fechamento', 'Volume', 'SMA_7', 'SMA_21', 'RSI', 'Sentimento_Medio']
    
    # Garantir que colunas existem
    if not all(col in df.columns for col in features):
        print("Erro: Colunas faltando.")
        return

    data_values = df[features].values
    scaler = MinMaxScaler(feature_range=(0, 1))
    scaled_data = scaler.fit_transform(data_values)
    
    last_60_days = scaled_data[-60:]
    X_input = last_60_days.reshape(1, 60, 6)
    
    # 5. PREVISÃO
    print("4. Executando IA...")
    if not os.path.exists('modelo_cripto.keras'):
        print("Erro: Modelo não encontrado.")
        return
        
    model = load_model('modelo_cripto.keras')
    prediction_scaled = model.predict(X_input, verbose=0)
    
    matriz_aux = np.zeros((1, 6))
    matriz_aux[:, 0] = prediction_scaled[:, 0] 
    prediction_usd = scaler.inverse_transform(matriz_aux)[0, 0]
    
    # --- NOVA LÓGICA DE DECISÃO (ZONA NEUTRA) ---
    preco_atual = df['Preco_Fechamento'].iloc[-1]
    
    # Calcula a variação percentual
    delta_percentual = ((prediction_usd - preco_atual) / preco_atual) * 100
    
    # Definição de Limiar (Threshold) de 0.5%
    # Se mudar menos que 0.5%, consideramos o mercado indeciso.
    limiar = 0.5 

    if delta_percentual > limiar:
        direcao = "SUBIR 📈 (Tendência Alta)"
        cor_log = "VERDE"
    elif delta_percentual < -limiar:
        direcao = "CAIR 📉 (Tendência Baixa)"
        cor_log = "VERMELHO"
    else:
        direcao = "LATERAL 😐 (Mercado Neutro)"
        cor_log = "AMARELO"

    print("\n" + "="*40)
    print(f"💰 PREÇO ATUAL (Hoje):   ${preco_atual:,.2f}")
    print(f"🔮 PREVISÃO (Amanhã):    ${prediction_usd:,.2f}")
    print("-" * 40)
    print(f"📊 VARIAÇÃO: {delta_percentual:+.2f}%")
    print(f"🧭 VEREDITO: {direcao}")
    print("="*40)

    # Dica para Debug: Salvar log para ver se o modelo não está apenas copiando o valor
    print(f"[DEBUG] Diferença absoluta: ${prediction_usd - preco_atual:.2f}")

if __name__ == "__main__":
    pipeline_previsao_final()
