# -*- coding: utf-8 -*-
"""processamento_sentimento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jcu35yBqsb5GA3-H2EViaLeG2lZ_KfiK
"""

!pip install vaderSentiment -q

import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from dateutil import parser

def processar_sentimento_diario():
    print("--- 1. PROCESSANDO SENTIMENTO DIÁRIO ---")

    # Carregar as notícias brutas
    try:
        df = pd.read_csv('noticias_bitcoin.csv', sep=';')
    except FileNotFoundError:
        print("Erro: 'noticias_bitcoin.csv' não encontrado. Rode a coleta qualitativa antes.")
        return None

    # Inicializar VADER
    analyzer = SentimentIntensityAnalyzer()

    # 1. Calcular Score para cada manchete
    print("Calculando scores individuais...")
    df['compound'] = df['Titulo'].apply(lambda x: analyzer.polarity_scores(str(x))['compound'])

    # 2. Tratamento de Data (Essencial para cruzar com o Bitcoin)
    # O GNews retorna datas complexas, vamos simplificar para YYYY-MM-DD
    def limpar_data(data_str):
        try:
            # Tenta entender o formato automaticamente
            dt = parser.parse(str(data_str))
            return dt.strftime('%Y-%m-%d')
        except:
            return None

    df['Data_Limpa'] = df['Data'].apply(limpar_data)

    # Remover datas que falharam
    df.dropna(subset=['Data_Limpa'], inplace=True)

    # 3. AGRUPAR POR DIA (A Média do Sentimento diário)
    # Aqui está a mágica: transformamos várias notícias num único número do dia
    df_diario = df.groupby('Data_Limpa')['compound'].mean().reset_index()

    # Renomear para facilitar o merge depois
    df_diario.columns = ['Data', 'Sentimento_Medio']

    # Salvar
    arquivo_saida = 'sentimento_diario.csv'
    df_diario.to_csv(arquivo_saida, index=False, sep=';')

    print(f"Sucesso! Sentimento diário salvo em '{arquivo_saida}'")
    print(df_diario.tail())
    return df_diario

if __name__ == "__main__":
    processar_sentimento_diario()